// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Person struct {
	ID        uuid.UUID
	FullName  string
	Email     string
	Avatar    string
	Location  string
	Metadata  []byte
	CreatedAt pgtype.Timestamp
}

type PersonsRanking struct {
	ID          uuid.UUID
	PersonID    uuid.UUID
	SearchCount int32
	CreatedAt   pgtype.Timestamp
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}
